apiVersion: scans.aquasec.community/v1alpha1
kind: ImageScan
metadata:
  labels:
    app.kubernetes.io/name: aqua-scan-triggerer
    app.kubernetes.io/managed-by: kustomize
  name: imagescan-sample
spec:
  image: nginx:latest
  digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
